-- -*- mode: lua; coding: windows-1251-dos -*-
--*********************************************************************************************************
--==============================================================================================
log1("--LUA version: ["..(jit.version or _VERSION).."]")
--==============================================================================================
FFI = require('ffi') --Делать только здесь и только один раз!
--==============================================================================================
math.randomseed(os.time())
--====================================[LuaFileSystem]===========================================
--lfs.dll должен быть в папке bin.
--xpcall(function() require("lfs") end, log1)
--=======================================[LuaXML]===============================================
--_luaxml.script должен быть в папке scripts.
--prefetch("_luaxml")
--===================[string.lower и string.upper с поддержкой русских букв]====================
--[=[--KRodin: Из-за setlocale могут возникать проблемы.
os.setlocale("", "ctype") --Для старых версий LuaJIT достаточно установить правильную локаль.
if jit.version_num >= 20000 then --В новых версиях установки локали недостаточно
	FFI.cdef[[
		int tolower( int code );
		int toupper( int code );
	]]
	string.lower = function(s)
		return s:gsub('.', function(x)
			return string.char( FFI.C.tolower( x:byte() ) )
		end)
	end
	string.upper = function(s)
		return s:gsub('.', function(x)
			return string.char( FFI.C.toupper( x:byte() ) )
		end)
	end
end
--]=]
do
	local lower = string.lower
	string.lower = function(s)
		return lower(s:gsub("([А-Я])",function(c) return string.char(c:byte()+32) end):gsub("Ё", "ё"))
	end
	--
	local upper = string.upper
	string.upper = function(s)
		return upper(s:gsub("([а-я])",function(c) return string.char(c:byte()-32) end):gsub("ё", "Ё"))
	end
end
--=================================[Функции из xrLuaFix]========================================
--Cрезать первое "слово"
string.trim_w = function(s) return s:gsub("%s-(%S+)%s+", '', 1) end
--Срезать пробелы слева
string.trim_l = function(s) return s:gsub("^%s+", '') end
--Срезать пробелы справа
string.trim_r = function(s) return s:gsub("%s*$", '') end
--Срезать пробелы слева и справа
string.trim   = function(s) return s:match( "^%s*(.*%S)" ) or "" end
------------------------------------------------------------------------------------------------
--Возвращает кол-во элементов в таблице. Для массивов надо использовать оператор #.
table.size = function(t)
	local size = 0
	for _ in pairs(t) do size = size + 1 end
	return size
end
--Возвращает случайный элемент массива. Для обычных таблиц такое делать нет никакого смысла. В движке было сделано как-то странно.
table.random = function(t)
	return t[math.random(#t)]
end
--Возвращает массив с ключами таблицы
table.keys = function(t)
	local arr = {}
	for k, _ in pairs(t) do
		table.insert(arr, k)
	end
	return arr
end
--Возвращает массив с значениями таблицы
table.values = function(t)
	local arr = {}
	for _, v in pairs(t) do
		table.insert(arr, v)
	end
	return arr
end
--==============================================================================================
-- Взято из аддона Naxac'a
local to_ptrn = {
	[' '] = '%s',
	['.'] = '%.',
	['%'] = '%%',
	['*'] = '%*',
	['-'] = '%-'
}
string.explode = function( div,    -- разделитель
                           str,    -- строка
                           clear ) -- обрезать ли пробелы по краям строк (false/true)
	local ret = {}
	for s in str:gmatch("([^"..(to_ptrn[div] or div).."]+)") do
		ret[#ret+1] = (clear and s:trim() or s)
	end
	return ret
end
--==============================================================================================
-- очистка строки от "лишних" символов (полезно при работе с FS)
string.clear = function(str) --KRodin: поправил функцию, теперь работает.
	return str:gsub( '[/:<>|%*%?"\\]*', "" )
end
--==============================================================================================
-- Форматирование текста по ширине
-- http://www.amk-team.ru/forum/topic/13216-sborochnyy-ceh/?do=findComment&comment=959286
string.width = function(str, width, return_table, indent, paragrapf)
    indent    = indent    or 0
    paragrapf = paragrapf or 0
    width     = (width or 80) - indent

    local i = string.rep(' ', indent)
    local t = {}
    local line = string.rep(' ', paragrapf)

    for exp, word in str:gmatch('(%s-(%S+))') do
        if line == '' and #t ~= 0 then
            exp = word
        end

        local l_len = #line
        local len = l_len + #exp
        
        if len > width then
            t[#t+1], line = line, word
        else
            line = line .. exp
            if l_len == width then
                t[#t+1], line = line, ''
            end
        end
    end

    t[#t+1] = line

    if return_table then
        return t
    else
        return i .. table.concat(t, '\n' .. i)
    end
end
--==============================================================================================
function table.copy(tbl) --Возвращает копию таблицы.
	local mt = getmetatable(tbl)
	local res = {}
	for k, v in pairs(tbl) do
		if type(k) == "table" then
			k = table.copy(k)
		end
		if type(v) == "table" then
			v = table.copy(v)
		end
		res[k] = v
	end
	setmetatable(res, mt)
	return res
end
--=================================[CUIScriptWnd Extension]=====================================
-- Вызов обычный, как и в AddCallback, но после последнего аргумента можно передавать множество дополнительных.
function CUIScriptWnd:Connect(name, event, func, ...)
	local args = {...}
	return self:AddCallback( name, event, function() func(unpack(args)) end )
end
--==============================================================================================
local tostring_all_tbl = {
    ["table"] 	   = function(table, ind) --Распечатка таблиц
                        local res = "{" --Начало
                        local end_res = ind and "\n"..ind.."}" or "\n}" --Конец
                        local def_ind = "  " --Отступ от начала строки
                        ind = ind and ind..def_ind or def_ind --Для каждой "таблицы внутри таблицы" отступ увеличивается в 2 раза
                        for k, v in pairs(table) do
                            res = res.."\n"..ind.."["..tostring_all(k, ind).."] = "..tostring_all(v, ind)..","
                        end
                        return res..end_res
                    end,
    ["string"]    = function(v) return "'"..v.."'" end, --Строки берём в кавычки. Это нужно, чтобы можно было отличить строку "123" от числа 123, "nil" от nil и тд...
    ["number"]    = function(v) return tostring(v) end,
    ["boolean"]   = function(v) return tostring(v) end,
    ["nil"]       = function(v) return tostring(v) end,
    ["function"]  = function() return "[[FUNCTION]]" end, --Function, Userdata и Thread распечатать нельзя, просто заменим на строки
    ["userdata"]  = function() return "[[USERDATA]]" end,
    ["thread"]    = function() return "[[THREAD]]" end,
}
--Конвертирование чего угодно в строку. Использовать только для вывода в лог!
function tostring_all(obj, ind) --ind - служебный аргумент для распечатки "таблиц в таблицах".
	return tostring_all_tbl[type(obj)](obj, ind)
end

--Функциональная обёртка для log1.
--Делает дополнительную работу по конвертации параметров, которые не воспринимаются родной функцией string.format.
--Параметры можно передавать ЛЮБОГО ТИПА! В строке формата они должны стоять как %s (потому, что будут сконвертированы в строки).
function log3(fmt, ...)
	local args = {...}
	for i=1, #args do
		args[i] = tostring_all(args[i])
	end
	local res, msg = pcall(string.format, fmt, unpack(args))
	if not res then --Если произошла ошибка
		msg = "!!log3 failed: "..msg.."\n"..debug.traceback()
	end
	log1(msg)
end
--==============================================================================================
function abort(fmt, ...)
	log1("!!****************************[ABORT]*********************************")
	log1(debug.traceback())
	log3(fmt, ...)
	log1("!!********************************************************************")
	error(tostring(fmt))
end
function ASSERT(cond, ...)
	if not cond then
		abort(...)
	end
end
--==============================================================================================
function cmd(scmd, ...)
	ASSERT(scmd, "[cmd] scmd is a nil reference")
	local args = {...}
	if #args > 0 then
		scmd = scmd..' '..table.concat(args, ' ')
	end
	get_console():execute(scmd)
end
--==============================================================================================
log = function(...) --[[log1(...)]] end
--***************************************************************************************************************


schemes = {} -- соответствие схем модулям
stypes = {} -- типы схем

-- Загружает схему из файла на диске и активирует в мотиваторе.
-- Здесь:
-- 	filename - имя файла, в котором реализована схема, без расширения
-- 	scheme - имя схемы
function load_scheme(filename, scheme, stype)
	schemes[scheme] = filename
	stypes[scheme] = stype
end

----------------------------------------------------------------------

function printf(fmt,...)
	log(string.format(fmt,...))
end

----------------------------------------------------------------------
if nil == time_global then
	time_global = function () return device():time_global() end
end

function wait_game(time_to_wait)
    verify_if_thread_is_running()
    if (time_to_wait == nil) then
        coroutine.yield()
    else
        local time_to_stop = game.time() + time_to_wait
        while game.time() <= time_to_stop do
            coroutine.yield()
        end
    end
end

function wait(time_to_wait)
    verify_if_thread_is_running()
    if (time_to_wait == nil) then
        coroutine.yield()
    else
        local time_to_stop = time_global() + time_to_wait
        while time_global() <= time_to_stop do
            coroutine.yield()
        end
    end
end

function action(obj,...)
    local arg = {...}
    local act = entity_action()
    local i = 1
    while true do
        if (arg[i] ~= nil) then
            act:set_action(arg[i])
        else
            break
        end
        i = i + 1
    end
    if (obj ~= nil) then
        obj:command(act,false)
    end
    return  entity_action(act)
end

function action_first(obj,...)
    local arg = {...}
    local act = entity_action()
    local i = 1
    while true do
        if (arg[i] ~= nil) then
            act:set_action(arg[i])
        else
            break
        end
        i = i + 1
    end
    if (obj ~= nil) then
        obj:command(act,true)
    end
    return  entity_action(act)
end

function round (value)
    local min = math.floor (value)
    local max = min + 1
    if value - min > max - value then return max end
    return min
end

function debug_get_level_object(obj_name)
    local res = level.debug_object(obj_name)
    while res == nil do

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!!! НЕ ЗАКОММЕНТАРИВАЙТЕ, ИНАЧЕ НЕ БУДЕТ ВИДНО ОШИБОК ПРИ РАССТАНОВКЕ ОБЪЕКТОВ !!!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        printf("get_level_object() is waiting for object \"%s\"", obj_name)

        res         = level.object(obj_name)
        wait        ()
    end
    return          res
end

function debug_get_actor()
    local res       = level.debug_actor()
    while res == nil do
        res         = level.debug_actor()
        wait        ()
    end
    return          res
end

function distance_between(obj1, obj2)
    return obj1:position():distance_to(obj2:position())
end

// Если один объект nil, например нет актера, то считаем, что он далеко
function distance_between_safe(obj1, obj2)
    if(obj1 == nil or obj2 == nil) then return 100000 end
	return obj1:position():distance_to(obj2:position())
end


--' Проверка на инфопоршны, даже если игрока не существует
function has_alife_info(info_id)
	local aa = alife()
	if aa == nil then
		return false
	end
	return aa:has_info(0, info_id)
end


--------------------------------------------------
-- іласс LUA реализуі   ий Finite State Machine
-- для управления персонажами
--------------------------------------------------
class 'FSM'

--  инициализация путем задания объекта Non-Player Character
function FSM:__init(script_name, npc_obj)
    -- указатель на подконтрольнvй NPC
    self.npc = npc_obj
    -- строка - имя скрипта, которvй запускает игру
    self.script_name = script_name
    -- матрица, задаі   ая граф переходов состояний
    -- реализуется как двумерная таблица
    self.transition_matrix = {[0] = {}}
    -- номер теку   его состояния
    self.current_state = 0

    -- флаг того, что машина вклічена
    self.machine_running = true

    printf("inialization FSM for NPC %s", self.npc:name())
end

function FSM:is_running()
    return self.machine_running
end

function FSM:start()
    printf("starting FSM for %s", self.npc:name())
    self.machine_running = true
end

function FSM:stop()
    printf("stoping FSM for %s", self.npc:name())
    self.machine_running = false
    self:reset_script_control()
end


--  добавление указателя на булеву
--  функциі условия перехода
function FSM:set_transition(from_state_num, to_state_num, cond_func)
    printf("in setting transition %d, %d ", from_state_num, to_state_num)

    if self.transition_matrix[from_state_num] == nil then
       self.transition_matrix[from_state_num] = {[to_state_num] = cond_func}
    else
       self.transition_matrix[from_state_num][to_state_num] = cond_func
    end
end

-- единичная проверка FSM
function FSM:run()
    local transition_vector = self.transition_matrix[self.current_state]
    table.foreach(transition_vector,
                  function(to_state_num, cond_func)
                        if cond_func(self.npc, self) == true then
                            printf("transition from %d to %d", self.current_state, to_state_num)

                            if to_state_num == 0 then
                                self:reset_script_control()
                            end

                            --if  self.current_state == 0 then
                            --  self:set_script_control()
                            --end

                            self.current_state = to_state_num
                            return true
                        end
                        return nil
                  end)
end


-- запуск бесконечного цикла FSM
function FSM:run_loop()
    printf("running FSM loop for NPC %s", self.npc:name())

    while self:is_running() do
        local transition_vector = self.transition_matrix[self.current_state]
        table.foreach(transition_vector,
                      function(to_state_num, cond_func)
                            if cond_func(self.npc, self) == true then
                                printf("transition from %d to %d", self.current_state, to_state_num)

                                if to_state_num == 0 then
                                    self:reset_script_control()
                                end

                                --if  self.current_state == 0 then
                                --  self:set_script_control()
                                --end

                                self.current_state = to_state_num
                                return true
                            end
                            return nil
                      end)
        if self.npc:alive () == false then
           self.npc:script (false, self.script_name)
           return
           end
        wait()
    end
end

-- взятие под контроль скрипта NPC (переход из нулевого состояния)
function FSM:set_script_control()
    printf("set script control for FSM of NPC %s", self.npc:name())
    self.npc:script(true, self.script_name)
end

-- отпускание из под контроля скрипта NPC (переход в нулевое состояние)
function FSM:reset_script_control()
    printf("reset script control for FSM of NPC %s", self.npc:name())
    self.npc:script(false, self.script_name)
end

--------------------------------------------------
-- end of  class 'FSM'
--------------------------------------------------

function reset_action (npc, script_name)
    if npc:get_script () then
       npc:script (false, script_name)
    end
    npc:script (true, script_name)
end

class "script_object"

function script_object.__init(self,name,script,...)
	self.action         = action(nil,...)
	self.object_name    = name
	self.script_name    = script
	self.object         = nil
end

function script_object:update()
    local                   obj = self.object
    self.object             = level.object(self.object_name)
    if ((obj == nil) and (self.object ~= nil)) then
        self.object:script  (true,self.script_name)
        self.object:command (self.action,false)
    end
end

--
-- іередача персонажу информации
--

function GiveInfoViaPda(obj_receiver, obj_sender, info_number)
    obj_receiver:give_info_portion_via_pda(info_number, obj_sender)
end


--------------------------------------------------
-- Functions and variables added by Zmey
--------------------------------------------------

-- іонстанта, которуі использовать в местах, где нужно задать неограниченное время действия
time_infinite = 100000000

-- =азвание скрипта, которvй в даннvй момент находится в отладке
-- (в этом скрипте будут срабатvвать вvзовv функции debug_log)
debug_script_name = ""

-- Tvводит в лог строчку, если script_name == debug_script_name
-- Lспользуется для отрадки сценариев
function debug_log(script_name, fmt, ...)
	if debug_script_name == script_name then
		log(string.format(fmt, ...))
	end
end

-- +сли в даннvй момент вvполняется какое-то действие, прерvвает его и отклічает скриптовvй режим
function interrupt_action(who, script_name)
  if who:get_script() then
    who:script(false, script_name)
  end
end

function random_choice(...)
    local arg = {...}
    local r = math.random(1, table.getn(arg))
    return arg[r]
end

function new_action(...)
    local arg = {...}
    local act = entity_action()
    for i = 1, table.getn(arg) do
        act:set_action(arg[i])
    end
    return act;
end

obj_last_actions = {};

function perform_action(obj, action_name, action)
  if (obj ~= nil) then
    obj_last_actions[obj] = action_name
    obj:command(act, false)
  end
end

function last_action(obj)
  return obj_last_actions[obj]
end

function if_then_else(cond, if_true, if_false)
    if cond then
        return if_true
    end
    return if_false
end

function update_action (npc, script, ...)
    local arg = {...}
    if npc == nil then return end
    local act = npc:action ()
    if arg.n == 0 then return end

    if act == nil then act = entity_action () end

    for a = 1, arg.n, 1 do
        if arg[a] ~= nil then act:set_action (arg[a]) end
    end
    reset_action (npc, script)
    npc:command (act, false)

end


function set_current_time (hour, min, sec)
    local current_time_factor = level.get_time_factor ()

    printf ("Need time : %d:%d:%d", hour, min, sec)

    local current_time = game.time ()
    local c_day = math.floor (current_time / 86400000)
    local c_time = current_time - c_day * 86400000
    local n_time = (sec + min * 60 + hour * 3600) * 1000

    if c_time > n_time then c_day = c_day + 1 end
    n_time = n_time + c_day * 86400000

    level.set_time_factor (10000)
    while game.time () < n_time do wait () end

    level.set_time_factor (current_time_factor)
end



if (editor() == false) then
class "pp_effector" (effector)

function pp_effector:__init(effector_type,start_time,dest_power,life_time) super(effector_type,start_time)
    self.start_time = start_time
    self.stop_time  = start_time + life_time
    self.max_power  = dest_power
end

function pp_effector:process(pp)
    effector.process(self,pp)

    local curr_time = time_global()
    local d         = 0.0

    if curr_time < self.start_time then
        d           = 0.0
    else
        if curr_time < self.stop_time then
            d           = (curr_time - self.start_time) / (self.stop_time - self.start_time)
        else
            self.info   = self.max_power
            return      true
        end
    end

    local dual      = duality()
    local noise     = noise()
    local base      = color()
    local gray      = color()
    local add       = color()

    dual.h          = self.max_power.dual.h         * d
    dual.v          = self.max_power.dual.v         * d

    noise.grain     = self.max_power.noise.grain        * d
    noise.intensity     = self.max_power.noise.intensity    * d
    noise.fps       = self.max_power.noise.fps      * d

    base.r          = self.max_power.color_base.r       * d
    base.g          = self.max_power.color_base.g       * d
    base.b          = self.max_power.color_base.b       * d

    gray.r          = self.max_power.color_gray.r       * d
    gray.g          = self.max_power.color_gray.g       * d
    gray.b          = self.max_power.color_gray.b       * d

    add.r           = self.max_power.color_add.r        * d
    add.g           = self.max_power.color_add.g        * d
    add.b           = self.max_power.color_add.b        * d

    pp.gray         = self.max_power.gray           * d
    pp.blur         = self.max_power.blur           * d

    pp.dual         = dual
    pp.noise        = noise
    pp.color_base       = base
    pp.color_gray       = gray
    pp.color_add        = add

    self.info       = pp

    return              true
end

function pp_effector:finished()
    return          self.stop_time < time_global()
end

--
-- postprocess for rainbow
--
class "pp_linear_lerp" (effector)

function pp_linear_lerp:__init(effector_type,start_time,life_time,start_power,dest_power) super(effector_type,start_time)
    self.start_time = start_time
    self.stop_time  = start_time + life_time
    self.min_power  = start_power
    self.max_power  = dest_power
end

function pp_linear_lerp:process(pp)
    effector.process(self,pp)

    local curr_time = time_global()
    local d         = 0.0

    if curr_time < self.start_time then
        d           = 0.0
    else
        if curr_time < self.stop_time then
            d           = (curr_time - self.start_time) / (self.stop_time - self.start_time)
        else
            self.info   = self.max_power
            return      true
        end
    end

    local dual      = duality()
    local noise     = noise()
    local base      = color()
    local gray      = color()
    local add       = color()

    dual.h          = self.min_power.dual.h         + (self.max_power.dual.h        - self.min_power.dual.h     )   * d
    dual.v          = self.min_power.dual.v         + (self.max_power.dual.v        - self.min_power.dual.v     )   * d

    noise.grain     = self.min_power.noise.grain        + (self.max_power.noise.grain       - self.min_power.noise.grain    )   * d
    noise.intensity     = self.min_power.noise.intensity    + (self.max_power.noise.intensity   - self.min_power.noise.intensity)   * d
    noise.fps       = self.min_power.noise.fps      + (self.max_power.noise.fps         - self.min_power.noise.fps  )   * d

    base.r          = self.min_power.color_base.r       + (self.max_power.color_base.r      - self.min_power.color_base.r   )   * d
    base.g          = self.min_power.color_base.g       + (self.max_power.color_base.g      - self.min_power.color_base.g   )   * d
    base.b          = self.min_power.color_base.b       + (self.max_power.color_base.b      - self.min_power.color_base.b   )   * d

    gray.r          = self.min_power.color_gray.r       + (self.max_power.color_gray.r      - self.min_power.color_gray.r   )   * d
    gray.g          = self.min_power.color_gray.g       + (self.max_power.color_gray.g      - self.min_power.color_gray.g   )   * d
    gray.b          = self.min_power.color_gray.b       + (self.max_power.color_gray.b      - self.min_power.color_gray.b   )   * d

    add.r           = self.min_power.color_add.r        + (self.max_power.color_add.r       - self.min_power.color_add.r    )   * d
    add.g           = self.min_power.color_add.g        + (self.max_power.color_add.g       - self.min_power.color_add.g    )   * d
    add.b           = self.min_power.color_add.b        + (self.max_power.color_add.b       - self.min_power.color_add.b    )   * d

    pp.gray         = self.min_power.gray           + (self.max_power.gray          - self.min_power.gray       )   * d
    pp.blur         = self.min_power.blur           + (self.max_power.blur          - self.min_power.blur       )   * d

    pp.dual         = dual
    pp.noise        = noise
    pp.color_base       = base
    pp.color_gray       = gray
    pp.color_add        = add

    self.info       = pp

    return          true
end

function pp_linear_lerp:finished()
    return          self.stop_time < time_global()
end
--
-- end of postprocess for rainbow
--

----------------------------------------------------------------------------------------------------------------------
-- Evaluators
----------------------------------------------------------------------------------------------------------------------
-- зарезервированv id с номерами от 0 до 256 для создания стандартнvх эвалуаторов.

--Constant evaluator
class "const_evaluator" (property_evaluator)

function const_evaluator:__init (name, value) super (nil, name)
    self.value = value
end

function const_evaluator:evaluate()
    return          self.value
end

--Wait evaluator
class "wait_evaluator" (property_evaluator)

function wait_evaluator:__init (wait_time) super ()
    self.wait_time = wait_time
    self.first_call = true
    self.current_time = 0
end

function wait_evaluator:evaluate ()
    if self.first_call == true then
       self.first_call = false
       self.current_time = device ():time_global ()
       return false
    end

    local t = device():time_global () - self.current_time;
    if t > self.wait_time then return true end
    return false
end
--------------------------------------------------------------------------------
class "enabled_evaluator" (property_evaluator)

function enabled_evaluator:__init (name, storage) super ()
    self.a = storage
end

function enabled_evaluator:evaluate()
    return  self.a.enabled
end

end -- end of editor() == false


function str_split (str)

    local strlen = string.len (str)

    local parts = {{}, {}, {}, {}}
    local cpart = 1

    for a = 1, strlen, 1 do
        local char = string.byte (str, a)
        if char ~= 95 then
           table.insert (parts[cpart], char)
        else
           cpart = cpart + 1
           if cpart > 4 then break end
        end
    end

    if cpart ~= 4 then return "unknown", "stalker", 0, 0 end

    local str1 = string.char ()
    local str2 = string.char ()
    local str3 = string.char ()
    local str4 = string.char ()

    local ref = parts[1]
    for a = 1, table.getn (ref), 1 do
        str1 = string.format ("%s%c", str1, ref[a])
    end

    ref = parts[2]
    for a = 1, table.getn (ref), 1 do
        str2 = string.format ("%s%c", str2, ref[a])
    end

    ref = parts[3]
    for a = 1, table.getn (ref), 1 do
        str3 = string.format ("%s%c", str3, ref[a])
    end

    ref = parts[4]
    for a = 1, table.getn (ref), 1 do
        str4 = string.format ("%s%c", str4, ref[a])
    end

    printf ("%s %s %d %d", str1, str2, str3, str4)
    return str1, str2, (str3 + 1) - 1, (str4 + 1) - 1
end

function random_number (min_value, max_value)
    math.randomseed (device ():time_global ())
    if min_value == nil and max_value == nil then
      return math.random ()
    else
      return math.random (min_value, max_value)
    end
end

-- ‚аҐ¬п бгв®Є ў ¬б
-- —гЈ ©
local ms_per_day = 24 * 60 * 60 * 1000
function day_time()
    return math.mod( game.time(), ms_per_day )
end

--Time in hours
function local_hours()
    return math.floor( math.mod( game.time()/1000, 86400 )/ 3600 )
end

-- Ї абЁв бва®Єг ўЁ¤  "   , ЎЎЎ, ўўў..." ў в Ў«Ёжг { "   ", "ЎЎЎ", "ўўў", ... }
-- —гЈ ©
function parse_names( s )
    local t = {}
    for name in string.gfind( s, "([%w_\\]+)%p*" ) do
    --for name in string.gfind( s, "%s*([^%,]+)%s*" ) do
        table.insert( t, name )
    end

    return t
end


function parse_key_value( s, sep )
    local t = {}
	if s == nil then
		return nil
	end
	if not sep then
		sep = ","
	end
    local key, nam = nil, nil
    for name in string.gmatch(s, "([^"..sep.."]+)") do--string.gfind( s, "([%w_\\]+)%p*" ) do
		if key == nil then
			key = name
		else
			t[key] = name
			key = nil
		end
    end
    return t
end


-- Ї абЁв бва®Єг ўЁ¤  "n1, n2, n3..." ў в Ў«Ёжг { n1, n2, n3, ... } Ј¤Ґ n1, n2, n3... - жҐ«лҐ зЁб« 
-- —гЈ ©
--[[function parse_nums( s )
    local t = {}

    for entry in string.gfind( s, "([%w_\\]+)%p*" ) do
        table.insert( t, tonumber( entry ) )
    end

    return t
end]]

-- Ї абЁв бва®Єг ўЁ¤  "n1, n2, n3..." ў в Ў«Ёжг { n1, n2, n3, ... } Ј¤Ґ n1, n2, n3... - ¤а®Ў­лҐ зЁб« 
function parse_nums( s )
	local t = {}

	for entry in string.gfind( s, "([%d%.]+)%,*" ) do
		table.insert( t, tonumber( entry ) )
	end

	return t
end

-- Їа®ўҐапҐв, Ґбвм «Ё ®ЎкҐЄв ў ®­« ©­Ґ
function is_object_online(obj_id)
	return level.object_by_id(obj_id) ~= nil
end

function get_clsid(npc)
    if npc == nil then return nil end

	return npc:clsid()

--    if is_object_online(npc:id()) then
--      return npc:clsid()
--    else
--        return nil
--    end
end

-- Їа®ўҐапҐв ®аг¦ЁҐ «Ё нв® (ЇҐаҐ¤ ў вм game_object)
function isWeapon(object)
    local id = get_clsid(object)
    if id == nil then return false end

    if id == clsid.wpn_vintorez_s then return true
    elseif id == clsid.wpn_ak74_s then return true
    elseif id == clsid.wpn_lr300_s then return true
    elseif id == clsid.wpn_hpsa_s then return true
    elseif id == clsid.wpn_pm_s then return true
    elseif id == clsid.wpn_shotgun_s then return true
    elseif id == clsid.wpn_bm16_s then return true
    elseif id == clsid.wpn_svd_s then return true
    elseif id == clsid.wpn_svu_s then return true
    elseif id == clsid.wpn_rpg7_s then return true
    elseif id == clsid.wpn_val_s then return true
    elseif id == clsid.wpn_walther_s then return true
    elseif id == clsid.wpn_usp45_s then return true
    elseif id == clsid.wpn_groza_s then return true
    elseif id == clsid.wpn_knife_s then return true
    elseif id == clsid.wpn_grenade_launcher then return true
    elseif id == clsid.wpn_grenade_f1 then return true
    elseif id == clsid.wpn_grenade_rpg7 then return true
    elseif id == clsid.wpn_grenade_rgd5 then return true
    elseif id == clsid.wpn_grenade_fake then return true
    else return false end
end

--Tvчисляет yaw в радианах
function yaw( v1, v2 )
    return  math.acos( ( (v1.x*v2.x) + (v1.z*v2.z ) ) / ( math.sqrt(v1.x*v1.x + v1.z*v1.z ) * math.sqrt(v2.x*v2.x + v2.z*v2.z ) ) )
end

function yaw_degree( v1, v2 )
    return  (math.acos( ( (v1.x*v2.x) + (v1.z*v2.z ) ) / ( math.sqrt(v1.x*v1.x + v1.z*v1.z ) * math.sqrt(v2.x*v2.x + v2.z*v2.z ) ) ) * 57.2957)
end
function yaw_degree3d( v1, v2 )
    return  (math.acos((v1.x*v2.x + v1.y*v2.y + v1.z*v2.z)/(math.sqrt(v1.x*v1.x + v1.y*v1.y + v1.z*v1.z )*math.sqrt(v2.x*v2.x + v2.y*v2.y + v2.z*v2.z)))*57.2957)
end

function vector_cross (v1, v2)
    return vector ():set (v1.y  * v2.z  - v1.z  * v2.y, v1.z  * v2.x  - v1.x  * v2.z, v1.x  * v2.y  - v1.y  * v2.x)
end

//Вращает вектор вокруг оси y против часовой стрелки

function vector_rotate_y (v, angle)
    angle = angle * 0.017453292519943295769236907684886
    local c = math.cos (angle)
    local s = math.sin (angle)
    return vector ():set (v.x * c - v.z * s, v.y, v.x * s + v.z * c)
end

-- очистка таблицы
function clear_table (t)
    while table.getn (t) > 0 do
          table.remove (t, table.getn (t))
    end
end

--€бЇ®«м§гҐв ¤«п ¬®­бва®ў. ‚лЎ®а в®зЄЁ, Єг¤  Ё¤вЁ ў ­ҐЄ®в®а®¬ а ¤ЁгбҐ Ё зв®Ў в®зЄ  Ўл«  ¤ «миҐ ­  а ббв®п­ЁЁ
-- min_radius ®в вҐЄгйҐ© Ї®§ЁжЁЁ(Ґб«Ё нв® Ї®«гзЁвбп). center_id - жҐ­ва Ї®§ЁжЁЁ, ў®ЄагЈ Є®в®а®© ¦ЁўҐ¬,
-- position_id - вгЄгй п Ї®§ЁжЁп, radius - ў Є Є®¬ а ¤ЁгбҐ ўлЎЁа вм в®зЄг, min_radius - ¬Ё­Ё¬ «м­®Ґ а ббв®п­ЁҐ, ®в вҐЄгйҐ© Ї®§ЁжЁЁ ¤® ­®ў®© в®зЄЁ.
function new_point(center_id, position_id,radius, min_radius)
    local dir = vector():set(math.random(-1000, 1000)/1000.0, 0.0001, math.random(-1000, 1000)/1000.0)
    local pos = level.vertex_in_direction(center_id, dir, radius)
    local i   = 1

    while(level.vertex_position(position_id):distance_to(level.vertex_position(pos) ) < min_radius and i < 20) do
        dir = vector():set(math.random(-1000, 1000)/1000.0, 0.0001, math.random(-1000, 1000)/1000.0)
        pos = level.vertex_in_direction(center_id, dir, radius)
        i   = i + 1
    end

    return (level.vertex_position(pos))
end

function stop_play_sound(obj)
	if obj:alive() == true then
		obj:set_sound_mask(-1)
		obj:set_sound_mask(0)
	end
end

function object_type(obj)
    local otype = get_clsid(obj)
    local type

    if  otype == clsid.actor or
        otype == clsid.script_stalker or
        otype == clsid.script_trader
    then
        type = "stalker"
    elseif  otype == clsid.crow or
        otype == clsid.zombie or
        otype == clsid.flesh or
        otype == clsid.controller or
        otype == clsid.bloodsucker or
        otype == clsid.burer or
        otype == clsid.chimera or
        otype == clsid.boar or
        otype == clsid.flesh_group or
        otype == clsid.dog_red or
        otype == clsid.dog_black or
        otype == clsid.pseudo_gigant
    then
        type = "monstr"
    elseif  otype == clsid.wpn_fn2000 or
        otype == clsid.wpn_ak74 or
        otype == clsid.wpn_lr300 or
        otype == clsid.wpn_hpsa or
        otype == clsid.wpn_pm or
        otype == clsid.wpn_fort or
        otype == clsid.wpn_binocular or
        otype == clsid.wpn_shotgun or
        otype == clsid.wpn_svd or
        otype == clsid.wpn_svu or
        otype == clsid.wpn_rpg7 or
        otype == clsid.wpn_val or
        otype == clsid.wpn_vintorez or
        otype == clsid.wpn_walther or
        otype == clsid.wpn_usp45 or
        otype == clsid.wpn_groza or
        otype == clsid.wpn_knife or
        otype == clsid.wpn_scope or
        otype == clsid.wpn_silencer or
        otype == clsid.wpn_grenade_launcher or
        otype == clsid.obj_physic or
        otype == clsid.obj_breakable or
        otype == clsid.device_pda or
        otype == clsid.device_torch or
        otype == clsid.device_detector_simple or
        otype == clsid.obj_bolt or
        otype == clsid.obj_medkit or
        otype == clsid.obj_food or
        otype == clsid.obj_bottle or
        otype == clsid.obj_antirad or
        otype == clsid.obj_explosive or
        otype == clsid.obj_document or
        otype == clsid.obj_attachable or
        otype == clsid.wpn_grenade_f1 or
        otype == clsid.wpn_grenade_rpg7 or
        otype == clsid.wpn_grenade_rgd5 or
        otype == clsid.wpn_grenade_fake or
        otype == clsid.equ_scientific or
        otype == clsid.equ_stalker or
        otype == clsid.equ_military or
        otype == clsid.equ_exo or
        otype == clsid.wpn_ammo or
        otype == clsid.wpn_ammo_vog25 or
        otype == clsid.wpn_ammo_og7b or
        otype == clsid.wpn_ammo_m209
    then
        type = "item"
    else
        type = "none"
    end

    -- Їа®ўҐапҐ¬ ­Ґ вагЇ «Ё нв®
    if type == "stalker" or
       type == "monstr" then
        if obj:alive() == false then
            type = "corpse"
        end
    end

    return type
end


// Является ли оbj монстром
function is_object_monster(obj)
	local otype = get_clsid(obj)
	if(otype == clsid.crow			or
		otype == clsid.cat			or
		otype == clsid.zombie		or
		otype == clsid.flesh		or
		otype == clsid.controller	or
		otype == clsid.bloodsucker	or
		otype == clsid.burer		or
		otype == clsid.chimera		or
		otype == clsid.boar			or
		otype == clsid.dog_red		or
		otype == clsid.dog_black	or
		otype == clsid.poltergeist	or
		otype == clsid.pseudo_gigant  )
	then
		return true
	end

	return false
end

--ў®§ўа й Ґв Їа®Ё§ў®«м­го в®зЄг ЇгвЁ г Є®в®а®© гбв ­®ў«Ґ­ ЎЁв
function point_with_bit(patrol_path, bit, old_point)      -- old_point - Ё­¤ҐЄб в®зЄЁ, Є®в®аго ­Ґ ­ ¤® ўлЎЁа вм,
  local points = {}                                       -- Ї а ¬Ґва ­Ґ ®Ўп§ вҐ«м­л©( ­ ЇаЁ¬Ґа вҐЄгйҐ© в®зЄЁ )

    for i = 0, patrol_path:count()-1 do
      --„®Ў®ў«пҐ¬ ў в Ў«Ёжг в®зЄЁ б ­г¦­л¬ ЎЁв®¬
      if( patrol_path:flag(i, bit)) then
            --„®Ў ў«пҐ¬ в®зЄг Ґб«Ё old_point == nil Ё«Ё ­®ў п в®зЄ  ­Ґ б®ўЇ ¤ Ґв б old_point
            if(old_point == nil) then
                table.insert(points, patrol_path:point(i))
            elseif(old_point ~= i) then
                table.insert(points, patrol_path:point(i))
            end
        end
    end

    local number_point = table.getn(points)

    if(number_point == 0) then
        return nil
    elseif(number_point == 1) then
        return points[1]
    else
        return points[math.random(1, number_point)]
    end
end

--ў®§ўа й Ґв Їа®Ё§ў®«м­го в®зЄг ЇгвЁ г Є®в®а®© гбв ­®ў«Ґ­ ЎЁв
function point_with_bit_id(patrol_path, bit, old_point)        -- old_point - Ё­¤ҐЄб в®зЄЁ, Є®в®аго ­Ґ ­ ¤® ўлЎЁа вм,
    local points = {}                                          -- Ї а ¬Ґва ­Ґ ®Ўп§ вҐ«м­л©( ­ ЇаЁ¬Ґа вҐЄгйҐ© в®зЄЁ )

    for i = 0, patrol_path:count()-1 do
      --„®Ў®ў«пҐ¬ ў в Ў«Ёжг в®зЄЁ б ­г¦­л¬ ЎЁв®¬
      if( patrol_path:flag(i, bit)) then
            --„®Ў ў«пҐ¬ в®зЄг Ґб«Ё old_point == nil Ё«Ё ­®ў п в®зЄ  ­Ґ б®ўЇ ¤ Ґв б old_point
            if(old_point == nil) then
                table.insert(points, i)
            elseif(old_point ~= i) then
                table.insert(points, i)
            end
        end
    end

    local number_point = table.getn(points)

    if(number_point == 0) then
        return nil
    elseif(number_point == 1) then
        return patrol_path:level_vertex_id(points[1])
    else
        return patrol_path:level_vertex_id(points[math.random(1, number_point)])
    end
end

--‚®§ўа й Ґв Ё­¤ҐЄб б ¬®© Ў«Ё¦­Ґ© в®зЄЁ ЇгвЁ б § ¤ ­л¬ ЎЁв®¬, ®в вҐЄгйҐ© в®зЄЁ
function near_point_with_bit(point, patrol_path, bit)
    local new_point = nil
    local index     = nil
    local dist      = 1000.0

    for i = 0, patrol_path:count()-1 do
        if( patrol_path:flag(i, bit) ) then
            if(new_point == nil or patrol_path:point(i):distance_to(point) < dist) then
                --…б«Ё нв  в®зЄ  ЇҐаў п Ё§ ­ иҐ¤иЁебп, «ЁЎ® ®в ­ҐҐ Їгвм Ў«Ё¦Ґ, в® § Ї®¬Ё­ Ґ¬ ҐҐ
                new_point   = patrol_path:point(i)
                index       = i
                dist        = new_point:distance_to(point)
             end
        end
    end

    return index
end

-- ђҐЄгабЁў­ п а бЇҐз вЄ  в Ў«Ёжл
function print_table(table, subs)
  local sub
  if subs ~= nil then
    sub = subs
  else
    sub = ""
  end
  for k,v in pairs(table) do
    if type(v) == "table" then
      printf(sub.."%s:", tostring(k))
      print_table(v, sub.."    ")
    elseif type(v) == "function" then
      printf(sub.."%s:function", tostring(k))
    elseif type(v) == "userdata" then
      printf(sub.."%s:userdata", tostring(k))
    elseif type(v) == "boolean" then
	if v == true then
		printf(sub.."%s:true", tostring(k))
	else
		printf(sub.."%s:false", tostring(k))
	end
    else
      if v ~= nil then
        printf(sub.."%s:%s", tostring(k),v)
      else
        printf(sub.."%s:nil", tostring(k),v)
      end
    end
  end
end

-------------------------------------------------------------------------------------------
function switch_online (id)
    if id == -1 then return end
    local sim = alife ()
    if sim ~= nil then
       sim:set_switch_online  (id, true)
       sim:set_switch_offline (id, false)
    end
end
-------------------------------------------------------------------------------------------
function switch_offline (npc)
    if npc == nil or npc:alive () == false then return end
    local sim = alife ()
    if sim ~= nil then
       sim:set_switch_online  (npc:id (), false)
       sim:set_switch_offline (npc:id (), true)
    end
end
-------------------------------------------------------------------------------------------
function get_actor_id()
	if(level.actor() == nil) then return -1 end
	return level.actor():id()
end
-------------------------------------------------------------------------------------------
function IsMonster (object, class_id)
    local id = class_id or get_clsid (object)
    if id == clsid.boar_s or
       id == clsid.bloodsucker_s or
       id == clsid.dog_s or
       id == clsid.flesh_s or
       id == clsid.pseudodog_s or
       id == clsid.psy_dog_s or
       id == clsid.burer_s or
       id == clsid.cat_s or
       id == clsid.chimera_s or
       id == clsid.controller_s or
       id == clsid.fracture_s or
       id == clsid.poltergeist_s or
       id == clsid.gigant_s or
       id == clsid.zombie_s or
       id == clsid.tushkano_s or
       id == clsid.snork_s
    then
	    return true
	end
    return false
end
-------------------------------------------------------------------------------------------
function IsStalker (object, class_id)
    local id = class_id or get_clsid (object)
    if id == clsid.actor or id == clsid.script_stalker then
       return true
    end
    return false
end
-------------------------------------------------------------------------------------------
function IsHelicopter (object, class_id)
    local id = class_id or get_clsid (object)
    if id == clsid.script_heli then
       return true
    end
    return false
end
-------------------------------------------------------------------------------------------
function IsCar (object, class_id)
    local id = class_id or get_clsid (object)
    if id == clsid.car_s then
       return true
    end
    return false
end
-------------------------------------------------------------------------------------------
function IsZone (object, class_id)
    local id = class_id or get_clsid (object)
    if id == clsid.zone_bfuzz_s or
       id == clsid.zone_mbald_s or
       id == clsid.zone_galant_s or
       id == clsid.zone_mincer_s or
	   id == clsid.Z_AMEBA or
	   id == clsid.Z_MBALD or
	   id == clsid.Z_RADIO or
	   id == clsid.Z_NOGRAV or
	   id == clsid.Z_RUSTYH or
	   id == clsid.Z_TORRID
    then
	    return true
	end
    return false
end
-------------------------------------------------------------------------------------------
function level_object_by_sid( sid )
	local sim = alife()

	if sim then
		local se_obj = sim:story_object( sid )
		if se_obj then
			return level.object_by_id( se_obj.id )
		end
	end

	return nil
end

function id_by_sid( sid )
	local sim = alife()

	if sim then
		local se_obj = sim:story_object( sid )
		if se_obj then
			return se_obj.id
		end
	end

	return nil
end

function set_postprocess(name_ini_file)
	bind_stalker.post_process = postprocess.PostProcess(ini_file_cached(name_ini_file))
end
function remove_postprocess()
	bind_stalker.post_process = nil
end

function set_inactivate_input_time(delta)
	db.storage[db.actor:id()].disable_input_time = game.get_game_time()
	db.storage[db.actor:id()].disable_input_idle = delta
	level.disable_input()
end
-- Принимает: позицию положения, позицию куда смотреть, время сна в минутах.
function set_sleep_relocate(point, look, timeout)
	db.storage[db.actor:id()].sleep_relocate_time = game.get_game_time()
	db.storage[db.actor:id()].sleep_relocate_idle = timeout*60
	db.storage[db.actor:id()].sleep_relocate_point = point
	db.storage[db.actor:id()].sleep_relocate_look = look

	--set_inactivate_input_time(timeout*60)
	--db.actor:actor_sleep(0, timeout)
end

-- проверяет целую часть числа на нечётность
function odd( x )
	return math.floor( x * 0.5 ) * 2 == math.floor( x )
end

--' Усталость
function on_actor_critical_power()
	if has_alife_info("esc_trader_newbie") then
		game.start_tutorial("part_11_weakness")
	end
	if not has_alife_info("encyclopedy_tutorial_weakness") then
		db.actor:give_info_portion("encyclopedy_tutorial_weakness")
	end
end

function on_actor_critical_max_power()
end

function on_actor_stamina()
end

--' Кровотечение
function on_actor_bleeding()
	if has_alife_info("esc_trader_newbie") then
		game.start_tutorial("part_8_wound")
	end
	if not has_alife_info("encyclopedy_tutorial_wound") then
		db.actor:give_info_portion("encyclopedy_tutorial_wound")
	end
end

function on_actor_satiety()
end

--' Радиация
function on_actor_radiation()
	if has_alife_info("esc_trader_newbie") then
		game.start_tutorial("part_6_radiation")
	end
	if not has_alife_info("encyclopedy_tutorial_radiation") then
		db.actor:give_info_portion("encyclopedy_tutorial_radiation")
	end
end

--' Заклинило оружие
function on_actor_weapon_jammed()
	if has_alife_info("esc_trader_newbie") then
		game.start_tutorial("part_9_weapon")
	end
	if not has_alife_info("encyclopedy_tutorial_weapon") then
		db.actor:give_info_portion("encyclopedy_tutorial_weapon")
	end
end

function on_actor_knife_condition()
end

--' не может ходить изза веса
function on_actor_cant_walk_weight()
	if has_alife_info("esc_trader_newbie") then
		game.start_tutorial("part_14_overload")
	end
	if not has_alife_info("encyclopedy_tutorial_overload") then
		db.actor:give_info_portion("encyclopedy_tutorial_overload")
	end
end

--' пси воздействие
function on_actor_psy()
end

function get_texture_info(id_name, id_default)
	if not id_default then 
		id_default = id_name 
	end

	local task_info = GetTextureInfo(id_name or "", id_default)
	local r = task_info:get_rect()

	r.x2 = r.x2 - r.x1
	r.y2 = r.y2 - r.y1
	return task_info:get_file_name(), r
end

function start_game_callback()
	--
	m_netpk.attach()
	--
	task_manager.clear_task_manager()
	treasure_manager.clear_treasure_manager()
	xr_sound.clear_all_sound_object()
	dialog_manager.fill_phrase_table()
end

color_by_relation = {
	[0] = "%c[green]",
	[1] = "%c[default]",
	[2] = "%c[red]",
}
name_by_relation = {
	[0] = "friendly",
	[1] = "indifferent",
	[2] = "enemy",
}

color_by_reputation = {
	good = "%c[green]",
	neutral = "%c[default]",
	bad = "%c[red]",
}

color_by_relation_argb = {
	[0] = GetARGB(255, 0, 255, 0),
	[1] = GetARGB(255, 255, 255, 128),
	[2] = GetARGB(255, 255, 0, 0),
}

--рушійно-подібні константи
KNIFE_SLOT 			= 0
FIRST_WEAPON_SLOT	= 1
SECOND_WEAPON_SLOT 	= 2
GRENADE_SLOT 		= 3
APPARATUS_SLOT 		= 4
BOLT_SLOT 			= 5
OUTFIT_SLOT 		= 6
PDA_SLOT 			= 7
DETECTOR_SLOT 		= 8
TORCH_SLOT 			= 9
ARTEFACT_SLOT 		= 10
HELMET_SLOT 		= 11
BACKPACK_SLOT 		= 12
SLOTS_TOTAL 		= 13
NO_ACTIVE_SLOT 		= 255

NO_STORY_ID = 4294967295

--//для показу інфо про активний предмет та спорядження
SHOW_ACTIVE_ITEM_INFO = false
SHOW_GEAR_INFO = false


sys_ini = system_ini()
game_ini = game_ini()

CELL_W = 50
CELL_H = 50
UI_BASE_HEIGHT = 768
UI_BASE_WIDTH = 1024
function get_current_kx()
    return (device().height / device().width) / (UI_BASE_HEIGHT / UI_BASE_WIDTH)
end

function get_screen_center()
	return vector2():set(UI_BASE_WIDTH*0.5, UI_BASE_HEIGHT*0.5)
end

function read_if_exists(ltx, val_type, section, value, default)
	if ltx and ltx:line_exist(section,value) then
		if val_type == "r_string" then
			return ltx:r_string(section,value)
		elseif val_type == "r_bool" then
			return ltx:r_bool(section,value)
		elseif val_type == "r_float" then
			return ltx:r_float(section,value)
		elseif val_type == "r_u32" then
			return ltx:r_u32(section,value)
		elseif val_type == "r_s32" then
			return ltx:r_s32(section,value)			
		elseif val_type == "r_vector" then
			return ltx:r_vector(section,value)			
		end
	else
		return default
	end
end

function get_section_keys_and_values(section, ini_file)
	local ini = ini_file or sys_ini
	ASSERT(ini:section_exist(section), "get_section_keys: section '"..section.."' doesn't exist")
	local t = {}
	for i = 0, ini:line_count(section) - 1 do
		local _, key, v = ini:r_line(section, i, "", "")
		t[key] = v
	end
	return t
end

function is_osoznanie_mode(npc)
	return read_if_exists(sys_ini, "r_bool", npc:section(), "need_osoznanie_mode", false)
end

function get_inv_name(section)
	return sys_ini:r_string(section,"inv_name")
end

function get_inv_name_short(section)
	return read_if_exists(sys_ini, "r_string", section, "inv_name_short", get_inv_name(section))
end

function cobj_by_name(name)
	return level.object_by_id(sobj_by_name(name).id)
end

function sobj_by_name(name)
	return alife():object(name)
end

function hud_anim_exists(item, anim_name)
	return read_if_exists(sys_ini, "r_string", get_hud_sect(item), anim_name, nil)
end

function get_hud_sect(item)
	local sect = type(item) == "userdata" and item:section() or item
	return read_if_exists(sys_ini, "r_string", sect, "hud", nil)
end

function math.clamp(val, _min, _max)
	if _min > _max then 
		_min, _max = _max, _min 
	end
	
	if val < _min then
		val = _min
	elseif _max < val then
		val = _max
	end
	return val
end

function math.fsimilar(val1, val2, cmp)
	cmp = cmp or 0.00001
	return math.abs( val1 - val2 ) < cmp
end

--//службове акторське

function parent_is_actor(item)
	local parent = item:parent()
	return parent and parent:id() == 0
end

function actor_hands_free()
	local act_item = actor:active_item()
	local act_device = actor:active_device()
	return (not act_item or not act_item:is_pending()) and (not act_device or not act_device:is_pending()) and game.hud_motion_allowed() and not actor:ph_capture()
end
function actor_cant_walk()
	return get_actor_obj().condition.cant_walk
end
function actor_get_knife()
	return actor:item_in_slot(0)
end
function actor_get_grenade()
	return actor:item_in_slot(3)
end
function actor_get_bolt()
	return actor:item_in_slot(5)
end
function actor_get_outfit()
	return actor:item_in_slot(6)
end
function actor_get_pda()
	return actor:item_in_slot(7)
end
function actor_get_device()
	return actor:item_in_slot(8)
end
function actor_get_torch()
	return actor:item_in_slot(9)
end
function actor_get_artefact()
	return actor:item_in_slot(10)
end
function actor_get_helmet()
	return actor:item_in_slot(11)
end
function actor_get_backpack()
	return actor:item_in_slot(12)
end

function is_actors_pda(item)
	local se_obj = alife():object(item:id())
	return item:get_pda() and se_obj.owner_data and se_obj.owner_data.name == actor:character_name()
end

function actor_break_sprint()
	local actor_obj = get_actor_obj()
	if actor_obj:is_actor_sprinting() then
		actor_obj:set_state_wishful(move_command.mcAccel)
	end
end

function block_non_move_action(block)
	level.only_allow_movekeys(block)
    level.set_actor_allow_ladder(not block)
end

function is_power_device(obj)
	if not obj then
	return false end
	local se_obj = alife():object(obj:id())
	return se_obj and se_obj.power_level and se_obj.cur_power_sect
end
function is_corruptible(obj)
	local se_obj = alife():object(obj:id())
	return se_obj and se_obj.last_time_called
end
function is_plate_carrier(obj)
	if not obj then
	return false end
	-- if get_clsid(obj) ~= clsid.equ_stalker_s then
	-- return false end
	local se_obj = alife():object(obj:id())
	return se_obj and se_obj.plate_condition and se_obj.cur_plate_num
end
--//інфоповідомлення на худі, у рушійному стилі
function hud_add_info_message(static_id, text, ttl)
	local hud = get_hud()
	local static = hud:GetCustomStatic(static_id)
	if not static then
		static = hud:AddCustomStatic(static_id, true)
		if ttl then
			hud:GetCustomStatic(static_id).m_endTime = time_global()/1000 + ttl
		end
	end
	static:wnd():SetTextST(text)
end
function hud_remove_info_message(static_id)
	local hud = get_hud()
	local static = hud:GetCustomStatic(static_id)
	if static then
		hud:RemoveCustomStatic(static_id)
	end
end

function split_string(inputstr, sep, tonum)
	if not inputstr then
	return nil end
	if sep == nil then
		sep = "%s"
	end
	local t={}
	for str in string.gmatch(inputstr, "([^"..sep.."]+)") do
		table.insert(t, tonum and tonumber(str) or str)
	end
	return t
end

function add_time_delayed_action(delay_time, func)
	local delay = time_global() + delay_time * 1000
	function time_check()
		return time_global() >= delay
	end
	level.add_call(time_check, func)
end

function add_update_delayed_action(updates_count, func)
	function update_count_check()
		updates_count = updates_count-1 
		return updates_count == 0
	end
	level.add_call(update_count_check, func)
end

function has_fire_modes(wpn)
	local f_modes_str = read_if_exists(sys_ini, "r_string", wpn:section(), "fire_modes", nil)
    return f_modes_str and #split_string(f_modes_str, ",") > 1
end

function get_fire_mode_str(wpn)
	if wpn:get_gl_mode() then
		return string.format("(%s)", game.translate_string("st_gl_firemode"))
	end
	local f_modes_str = read_if_exists(sys_ini, "r_string", wpn:section(), "fire_modes", nil)
	if not f_modes_str then
		return ""
	end
	local firemode_tbl = split_string(f_modes_str, ",")
	local cur_firemode = wpn:get_weapon_m().cur_fire_mode
	local res = firemode_tbl[cur_firemode+1]
	res = (tonumber(res) ~= -1) and res or "A"
	return string.format("(%s)", res)
end

function get_fire_modes(wpn)
	if wpn:get_gl_mode() then
	return false end
	if not wpn:get_weapon_m() then
	return false end
	local f_modes_str = read_if_exists(sys_ini, "r_string", wpn:section(), "fire_modes", nil)
	if not f_modes_str then
	return false end
	return split_string(f_modes_str, ",")
end

function get_cur_ammo_sect(obj)
	local ammo_sect = read_if_exists(sys_ini, "r_string", obj:section(), obj:get_gl_mode() and "grenade_class" or "ammo_class", nil)
	local ammo_table = split_string(ammo_sect, ",")
	--return ammo_table[obj:get_ammo_type()+1]
	
	local wpn = obj:get_weapon()
	return wpn and wpn:get_ammo_sect() or ammo_table[1]
end

function get_cur_ammo2_sect(obj)
	local ammo_sect = read_if_exists(sys_ini, "r_string", obj:section(), obj:get_gl_mode() and "ammo_class" or "grenade_class", nil)
	local ammo_table = split_string(ammo_sect, ",")
	return ammo_table[obj:get_underbarrel_ammo_type()+1]
end

function get_ammo_sects(obj)
	local ammo_sect = read_if_exists(sys_ini, "r_string", obj:section(), "ammo_class", nil)
	local ammo_table = split_string(ammo_sect, ",")
	return ammo_table
end

function get_magazine_sects(obj)
	local ammo_sect = read_if_exists(sys_ini, "r_string", obj:section(), "magazine_class", nil)
	local ammo_table = split_string(ammo_sect, ",")
	return ammo_table
end

function get_ammo2_sects(obj)
	local ammo_sect = read_if_exists(sys_ini, "r_string", obj:section(), "grenade_class", nil)
	local ammo_table = split_string(ammo_sect, ",")
	return ammo_table
end

-- сделать предмет безусловно негруппируемым в окнах инвентаря
function set_item_ungroupable( item )
  local f = item:get_inventory_item_flags()
  f:set( global_flags.FIUngroupable, true )
  item:set_inventory_item_flags( f )
end

-- включить движковую группировку для предмета
function set_item_default_grouping( item )
  local f = item:get_inventory_item_flags()
  f:set( global_flags.FIUngroupable, false )
  item:set_inventory_item_flags( f )
end

-- сделать предмет безусловно непродаваемым, будет показан красным. Для
-- избежания глюков надо также выключать группируемость для этого предмета.
function set_item_always_untradable( item )
  local f = item:get_inventory_item_flags()
  f:set( global_flags.FIAlwaysUntradable, true )
  item:set_inventory_item_flags( f )
end

-- убрать принудительную неторгуемость и негруппирумость и оставить только
-- движковый алгоритм
function set_item_default_tradability( item )
  local f = item:get_inventory_item_flags()
  f:set( global_flags.FIAlwaysUntradable, false )
  item:set_inventory_item_flags( f )
end

-- сделать предмет невидимым в инвентаре
function set_item_inv_hidden( item )
  local f = item:get_inventory_item_flags()
  f:set( global_flags.FIHiddenForInventory, true )
  item:set_inventory_item_flags( f )
end

-- сделать его обратно видимым
function set_item_inv_visible( item )
  local f = item:get_inventory_item_flags()
  f:set( global_flags.FIHiddenForInventory, false )
  item:set_inventory_item_flags( f )
end

function get_inv_item_hidden(item)
	local f = item:get_inventory_item_flags()
	return f:test( global_flags.FIHiddenForInventory )
end

-- Покрасить предмет в окнах обыска тайников/трупов в зелёный цвет
function set_item_always_highlighting( item )
  local f = item:get_inventory_item_flags()
  f:set( global_flags.FIAlwaysHighlighted, true )
  item:set_inventory_item_flags( f )
end

-- использовать только движковую раскраску
function set_item_default_highlighting( item )
  local f = item:get_inventory_item_flags()
  f:set( global_flags.FIAlwaysHighlighted, false )
  item:set_inventory_item_flags( f )
end

function need_show_condition(item)
	local b = sys_ini:r_bool(item:section(), "show_condition", nil)
	return ( ( item:is_weapon() or item:is_outfit() ) and b ~= false ) or b == true
end

function set_item_always_ungroupable( obj, flag )
  obj:get_inventory_item().always_ungroupable = flag
end

function wpn_IsRotatingToZoom( wpn )
  return wpn:get_weapon().zoom_rotation_factor < 1
end

function get_wpn_scope_zoom_params(item)
	local wpn = item:get_weapon_m()
	if not wpn or not wpn:is_addon_attached(addon.scope) then
	return nil end
	local sect = wpn:addon_attachable(addon.scope) and wpn:get_addon_name(addon.scope) or item:section()
	local zoom_params = split_string(read_if_exists(sys_ini, "r_string", sect, "scope_zoom_factor", nil), ",")
	return zoom_params
end

--обертає вектор навколо осі Y проти годинникової стрілки
function vector_rotate_y (v, angle)
    angle = angle * 0.017453292519943295769236907684886
    local c = math.cos(angle)
    local s = math.sin(angle)
    return vector():set (v.x * c - v.z * s, v.y, v.x * s + v.z * c)
end

function drop_item_to_angle(owner, item, angle)
    local dir = vector_rotate_y(owner:is_actor() and device().cam_dir or owner:direction(), angle)
    if (dir.y < 0) then dir.y = -dir.y end
    dir:normalize():mul(2)
    owner:drop_item_and_throw(item, dir)	
end

function is_actor_looking_to_pos(pos, radius)
	local k = vector():sub(pos, device().cam_pos)
	local b = k:dotproduct(device().cam_dir)
	local c = k:dotproduct(k) - radius * radius
	local d = b * b - c
	return d >= 0
end

function get_custom_logic_ini(obj)
	local custom_logic_ini = read_if_exists(sys_ini, "r_string", obj:section(), "logic_cfg", nil)
	if custom_logic_ini then
		return ini_file_cached(custom_logic_ini)
	end
	return nil
end

function is_ammo(section)
	return sys_ini:r_string(section,"class") == "AMMO"
end

function is_quest_item(section)
	return read_if_exists(sys_ini, "r_string", section, "quest_item", false)
end

--//заповнює глобальні таблиці lv_ids та gv_ids валідними левел- та гейм-вертексами відповідно
--//ключ таблиці - ім'я ігрової локації
function fill_vertex_data()
	lv_ids, gv_ids = {}, {}
	local i = 0
	local vertex, lvid, level_name
    while game_graph():valid_vertex_id(i) do
		vertex = game_graph():vertex(i)
		lvid = vertex:level_vertex_id()  --получаем левел вертекс по гейм вертексу 
        level_name = alife():level_name(vertex:level_id()) --получаем имя уровня по его номеру из секции в  game_graph
        if not lv_ids[level_name] then
			lv_ids[level_name] = {}   
        end
		table.insert(lv_ids[level_name], lvid) --заповнюємо таблицю левел-вертексів		
        if not gv_ids[level_name] then
            gv_ids[level_name] = {}
        end
		table.insert(gv_ids[level_name], i) --заповнюємо таблицю гейм-вертексів
		i = i+1
    end
end

--//повертає перший знайдений валідний level-vertex для вказаної локації
function get_any_lvid_by_level(level_name)
	if not lv_ids then
		fill_vertex_data()
	end
	return lv_ids[level_name][1]
end

--//повертає перший знайдений валідний game-vertex для вказаної локації
function get_any_gvid_by_level(level_name)
	if not gv_ids then
		fill_vertex_data()
	end
	return gv_ids[level_name][1]
end

--//спавн по координатам та імені рівня
--//ТІЛЬКИ для об'єктів яким НЕ ПОТРІБНА прив'язка до АІ-сітки
function spawn_to_level(section, spawn_pos, level_name, spawn_dir)
	local sim = alife()
	spawn_dir = spawn_dir or vector()
	local s_obj = sim:create(section, spawn_pos, -1, get_any_gvid_by_level(level_name))
	s_obj.angle = spawn_dir
	sim:object(s_obj.id):used_ai_locations(false)
	return s_obj
end

function spawn_ammo_to_level(section, spawn_pos, level_name, count, ammo_type, spawn_dir)
	ammo_type = ammo_type or 0
	spawn_dir = spawn_dir or vector()
	local sim = alife()	
	local gvid = get_any_gvid_by_level(level_name)
	local count_in_box = read_if_exists(sys_ini, "r_s32", section, "box_size", 1)
	local s_obj
	while count > count_in_box do
		s_obj = sim:create_ammo(section, spawn_pos, -1,	gvid, -1, count_in_box, ammo_type)
		s_obj.angle = spawn_dir
		sim:object(s_obj.id):used_ai_locations(false)
		count = count - count_in_box
	end
	s_obj = sim:create_ammo(section, spawn_pos, -1,	gvid, -1, count, ammo_type)	
	s_obj.angle = spawn_dir
	sim:object(s_obj.id):used_ai_locations(false)
end

--//спавн до inventory_owner'a
function spawn_to_owner(section, owner_id)
	owner_id = owner_id or actor:id()
	return alife():create(section, vector(), -1, -1, owner_id)
end

function spawn_ammo_to_owner(section, owner_id, count, ammo_type)
	owner_id = owner_id or actor:id()
	ammo_type = ammo_type or 0
	local count_in_box = sys_ini:r_u32(section, "box_size")
	count = count or count_in_box
	local sim = alife()
	
	local spawned = {}
	local sobj
	
	while count > count_in_box do
		sobj = sim:create_ammo(section, vector(), -1,	-1, owner_id, count_in_box, ammo_type)
		table.insert(spawned, sobj)
		count = count - count_in_box
	end
	sobj = sim:create_ammo(section, vector(), -1,	-1, owner_id, count, ammo_type)
	table.insert(spawned, sobj)
	return spawned
end

--спеціально для видачі пачок набоїв враховуючи магазини
--параметри count, loaded_box, ammo_type необов'язкові (одна повна пачка та перший з переліку тип за замовчуванням)
--count - кількість пачок
--loaded_box - повна чи порожня пачка
--ammo_type - тип набою у пачці (для магазинів)
--можна видавати порожні пачки (для магазинів)
function give_ammo_box_to_actor(section, count, loaded_box, ammo_type)
	count = count ~= nil and count or 1
	loaded_box = loaded_box ~= nil and loaded_box or true
	ammo_type = ammo_type ~= nil and ammo_type or 0
	local count_in_box = loaded_box and sys_ini:r_u32(section, "box_size") or 0
	while count > 0 do
		spawn_ammo_to_owner(section, actor:id(), count_in_box, ammo_type)
		count = count - 1
		news_manager.relocate_item(actor, "in", section)
	end
end

function time_to_table(time_struct)
	local Y, M, D, h, m, s, ms = time_struct:get(Y, M, D, h, m, s, ms)
	local time_table = {Y, M, D, h, m, s, ms}
	return time_table
end

function table_to_time(time_table)
	local time_struct = game.CTime()
	time_struct:set(time_table[1], time_table[2], time_table[3], time_table[4], time_table[5], time_table[5], time_table[7])
	return time_struct
end

function has_enemy_near(victim, radius)
	local enemy_near = false
	function perform_action(obj)
		if obj:is_stalker() or obj:is_monster() then
			if obj:alive() and obj:is_relation_enemy(victim) then
				--log3("creature %s is enemy to %s", obj:name(), victim:name())
				enemy_near = true
			end
		end
	end
	level.iterate_nearest(victim:position(), radius, perform_action)
	return enemy_near
end

local ini_file_cache = {}
function ini_file_cached(fname)
	if not ini_file_cache[fname] then
		ini_file_cache[fname] = ini_file(fname)
	end
	return ini_file_cache[fname]
end

function get_immunities_sect(section)
	return read_if_exists(sys_ini, "r_string", section, "immunities_sect", nil)
end

function get_bone_protection_sect(section)
	return read_if_exists(sys_ini, "r_string", section, "bones_koeff_protection", nil)
end

function is_3d_pda()
	return actor_get_pda() and actor_get_pda():is_hud_item() and get_console():get_bool("g_3d_pda")
end

function get_species(npc)
	return read_if_exists(sys_ini, "r_string", npc:section(), "species", "NO SPECIES")
end

local immunity_type = {
	"burn",
	"shock",
	"strike",
	"wound",
	"radiation",
	"telepatic",
	"chemical_burn",
	"explosion",
	"fire_wound",
	"wound_2",
	"physic_strike",
}
function get_hit_type_name(hit_type)
	return immunity_type[hit_type+1]
end

function aim_camera_to_pos(pos)
	if is_actor_looking_to_pos(pos, 0.01) then
	return end
	local dir = vector():sub(pos, device().cam_pos)
	local h = -dir:getH()
	local p = -dir:getP()
	local cam = actor_camera( 0 )
	if cam then
		cam.yaw = h
		cam.pitch = p
	end
end

function aim_camera_to_target(obj)
	local pos = obj:center()
	pos.y = pos.y + obj:radius() * 0.5
	if is_actor_looking_to_pos(pos, 0.5) then
	return end
	local dir = vector():sub(pos, device().cam_pos)
	local h = -dir:getH()
	local p = -dir:getP()
	local cam = actor_camera( 0 )
	if cam then
		cam.yaw = h
		cam.pitch = p
	end
end

function teleport_actor(position, level_name)
	if (not level_name or level.name() == level_name) then
		actor:set_actor_position(position)
	else
		level.change_level(get_any_gvid_by_level(level_name), -1, position, actor:direction())
	end
end

--//перевірка наявності метода у об'єкту
--//by Zander_driver (amk-team форум)
function check_obj_has_method(obj, method_name)
	return obj and obj[method_name] and type(obj[method_name]) == 'function'
end

function change_game_time(days, hours, minutes)
	level.change_game_time(days, hours, minutes)
	level_weathers.get_weather_manager():select_weather(true)
end

function detach_addon(item, addon_sect, not_spawn_addon)
	ogse_signals.get_mgr():call("on_before_addon_detach", item, addon_sect)	
	item:get_weapon_m():detach_addon(addon_sect, not not_spawn_addon)
	ogse_signals.get_mgr():call("on_addon_detach", item, addon_sect)
end