--[[

Weather transitions are only ever initiated by the engine on the hour. Thus, if we call
level.set_weather(weather_name, false) at 13:01, it will take 59 minutes for the transition to
weather_name to begin, and then 1 more hour before the transition is complete at 15:00.

In vanilla, dynamic weather transitions are requested right after the hour. In the SRP, they are
requested on the first actor binder update after 59 minutes past the hour. That way, they will be
initiated by the engine within one game minute of being requested by level.set_weather().

]]

function attach(sm)
	sm:subscribe({signal = "on_spawn", 			fun = this.on_spawn})
	sm:subscribe({signal = "on_update", 		fun = this.update})
	sm:subscribe({signal = "on_save", 			fun = this.save_weather})
	sm:subscribe({signal = "on_load", 			fun = this.load_weather})
	sm:subscribe({signal = "on_after_time_change", 	fun = this.reset})
end

local graphs_ini = ini_file_cached("environment\\dynamic_weather_graphs.ltx")

local weather_data = {
	current_weather = "[default]",
	target_weather = "[default]",
	need_hourly_update = false,
	graphs = {},
	weather_condlist = xr_logic.parse_condlist(nil, nil, nil, read_if_exists(game_ini, "string", level.name(), "weathers", "[default]")),
}

function on_spawn()
	if not weather_data.saved_state then
		--log_news("reset weather on_spawn")
		reset()
	end
end

function reset()
	select_weather(true)
end

-- Обновляем погоду раз в час.
function update()
	if level.get_time_minutes() < 59 then
		weather_data.need_hourly_update = true
	elseif weather_data.need_hourly_update then
		select_weather(false)
		weather_data.need_hourly_update = false
	end
end

local function get_next_state(graph)
	local sum = 0
	for _, prob in pairs (graph) do
		sum = sum + prob
	end
	local rnd = math.random() * sum
	local next_state
	for state, prob in pairs (graph) do
		next_state = state
		rnd = rnd - prob
		if rnd <= 0 then
			break
		end
	end
	return next_state
end

function select_weather(now)
	local weather_name = xr_logic.pick_section_from_condlist(actor, actor, weather_data.weather_condlist)
	local graph = get_graph_by_name(weather_name)
	local weather_section = graph == nil and weather_name or get_next_state(graph)
	
	--log_news("select_weather [%s] now [%s]", weather_section, now)
	level.set_weather(weather_section, now)

	weather_data.current_weather = now and weather_section or weather_data.target_weather
	weather_data.target_weather = weather_section
end

function set_state_from_string(state_string)
	local loaded_weather
	if string.find(state_string, "=", nil, true) then
		loaded_weather = string.match(state_string, "=([^,]+)") -- for save compatibility
	else
		loaded_weather = state_string
	end
	--log_news("set_state_from_string [%s]", loaded_weather)
	level.set_weather(loaded_weather, true)
	weather_data.current_weather = loaded_weather
	weather_data.target_weather = loaded_weather
end

function get_state_as_string()
	if level.get_time_minutes() >= 30 and weather_data.need_hourly_update then
		return weather_data.target_weather
	end
	return weather_data.current_weather
end

local function parse_ini_section_to_array(ini,section)
	local tmp=nil
	if ini and ini:section_exist(section) then
		tmp={}
		local result, id, value = nil, nil, nil
		for a=0,ini:line_count(section)-1 do
			result, id, value = ini:r_line(section,a,"","")
			if id~=nil and string.trim(id)~="" and string.trim(id)~=nil then
				tmp[string.trim(id)]=string.trim(value)
			end
		end
	end
	return tmp
end

function get_graph_by_name(name)
	if not weather_data.graphs[name] then
		weather_data.graphs[name] = parse_ini_section_to_array(graphs_ini, name)
	end
	return weather_data.graphs[name]
end

function load_weather()
	weather_data.saved_state = xr_vars.load_var("weather_saved", weather_data.saved_state)
	if weather_data.saved_state then
		--log_news("load_weather [%s]", weather_data.saved_state)
		set_state_from_string(weather_data.saved_state)	
	end
end

function save_weather()
	weather_data.saved_state = get_state_as_string()
	xr_vars.save_var("weather_saved", weather_data.saved_state)
	--log_news("save_weather [%s]", weather_data.saved_state)
	--log3("~on save weather - weather data %s", weather_state)
end