-- -*- mode: lua; coding: windows-1251-dos -*-
local hostile_threshold = sys_ini:r_float("game_relations", "attitude_neutral_threshold")
local friend_threshold = sys_ini:r_float("game_relations", "attitude_friend_threshold")

local index_for_community = {}
local communities_relations = {}
local community_for_index = {}

local function load_communities_relations()
    local index = 1

    for comm, id in string.gmatch(sys_ini:r_string("game_relations", "communities"), "([%w_]+)%s*,%s*([%d%.%-]+)%,*") do
        local t = {}
        for rel in string.gmatch(sys_ini:r_string("communities_relations", comm), "([%d%.%-]+)%,*") do
            table.insert(t, tonumber(rel))
        end
        communities_relations[comm] = t
        index_for_community[comm] = index
        community_for_index[index] = comm
        index = index + 1
    end
end

load_communities_relations() -- Построение таблиц делаем при первом запуске скрипта

function comm2idx(comm)
    return index_for_community[comm]
end

function idx2comm(id)
    return community_for_index[id]
end

function comm2comm_relation(community_from, community_to)
    local relations = communities_relations[community_from]
    ASSERT(relations, "")
    return relations[index_for_community[community_to]]
end

function community_relation_safe(community, npc)
    local relations = communities_relations[community]
    ASSERT(relations, "Can't find relation for community: [%s]", community or "nil")
	local char_comm = npc:character_community()
    return relations[index_for_community[char_comm]] + relation_registry.community_goodwill(community, npc:id())
end

function hostile(community, npc)
	return community_relation_safe(community, npc) < hostile_threshold
end

function friendly(community, npc)
	return community_relation_safe(community, npc) >= friend_threshold
end

function color(community, npc)
	local color = "%c[default]"
	local relation = community_relation_safe(community, npc)
	if relation < hostile_threshold then
		color = "%c[red]" 
	end
	if relation >= friend_threshold then
		color = "%c[green]"
	end
	return color
end

function color_by_val(val)
	local color = "%c[default]"
	if val < hostile_threshold then
		color = "%c[red]" 
	end
	if val >= friend_threshold then
		color = "%c[green]"
	end
	return color
end

function name(community, npc)
	local name = "indifferent"
	local relation = community_relation_safe(community, npc)
	if relation < hostile_threshold then
		name = "enemy" 
	end
	if relation >= friend_threshold then
		name = "friendly"
	end
	return name
end

function name_by_val(val)
	local name = "indifferent"
	if val < hostile_threshold then
		name = "enemy" 
	end
	if val >= friend_threshold then
		name = "friendly"
	end
	return name
end