-- -*- mode: lua; coding: windows-1251-dos -*-
function attach(sm)
	sm:subscribe({signal = "on_mouse_wheel", 		fun = this.on_mouse_wheel})
	sm:subscribe({signal = "on_key_press", 			fun = this.on_key_press})
	sm:subscribe({signal = "on_hud_state_switch", 	fun = this.on_state_switch})
	sm:subscribe({signal = "on_hud_item_zoom_in", 	fun = this.on_hud_item_zoom_in})
	sm:subscribe({signal = "on_hud_item_zoom_out", 	fun = this.on_hud_item_zoom_out})
end

-- local LOOKOUT_ANGLE_STEP = 5
-- local MIN_ANGLE = 30
-- local MAX_ANGLE = 60

local auto_lookout_dist = 1.5

local PH_BOX_ID_STEP = 2

local cam_height_factor = read_if_exists(sys_ini, "float", "actor", "camera_height_factor", 0.86)

local ph_box = {}
for i=0, 4 do
	local ph_box_center = read_if_exists(sys_ini, "vector", "actor", "ph_box"..i.."_center", nil)
	local ph_box_size = read_if_exists(sys_ini, "vector", "actor", "ph_box"..i.."_size", nil)
	if ph_box_center and ph_box_size then
		local _min = vector():set(ph_box_center)
		local _max = vector():set(ph_box_center)
		_min:sub(ph_box_size)
		_max:add(ph_box_size)
		local box_size = vector():sub(_max, _min)
		ph_box[i] = box_size
	end
end

function get_ph_box_min_max_id()
	if actor_obj:is_actor_creep() and not actor_obj:is_actor_creeping() then
		return 2, 4
	end
	if actor_obj:is_actor_crouch() and not actor_obj:is_actor_crouching() then
		return 1, 3
	end
	return nil
end

function on_mouse_wheel(forward)
	-- if not (IsMoveState(move_state.mcLookout) or IsMoveState(move_state.mcCrouch)) then
	if not IsMoveState(move_state.mcCrouch) then
	return end
	local active_item = actor:active_item()
	if active_item and active_item:is_zoomed() and has_dynamic_zoom(active_item) then
	return end
	
	-- if IsMoveState(move_state.mcLookout) then
		-- local step = forward and LOOKOUT_ANGLE_STEP or -LOOKOUT_ANGLE_STEP
		-- local current_angle = actor_obj.lookout_angle
		-- local desired_angle = math.clamp(actor_obj.lookout_angle + step, MIN_ANGLE, MAX_ANGLE)
		-- actor_obj.lookout_angle = desired_angle
	-- return end
	
	if IsMoveState(move_state.mcCrouch) then
		--log_news("~ph_box id [%s]", actor_obj.ph_box_id)
		local step = forward and PH_BOX_ID_STEP or -PH_BOX_ID_STEP
		local MIN_BOX_ID, MAX_BOX_ID = get_ph_box_min_max_id()
		if not MIN_BOX_ID then
		return end
		local desired_id = math.clamp(actor_obj.ph_box_id + step, MIN_BOX_ID, MAX_BOX_ID)
		actor_obj.ph_box_id = desired_id
		--log_news("~new ph_box id [%s]", actor_obj.ph_box_id)
	return end
end

local lookout_check = {
	[key_bindings.kL_LOOKOUT] = function() return IsMoveState(move_state.mcRLookout) end,
	[key_bindings.kR_LOOKOUT] = function() return IsMoveState(move_state.mcLLookout) end,
}
local wait_for_action
function on_key_press(key, game_action)
	if get_console():get_bool("g_hold_to_lookout") then
	return end
	if not lookout_check[game_action] or not lookout_check[game_action]() then
	return end
	if wait_for_action then
	return end
	wait_for_action = true
	level.add_call(
		function()
			return not IsMoveState(move_state.mcLookout)
		end,
		function()
			wait_for_action = false
			level.send_event_key_press(bind_to_dik(game_action))
			level.send_event_key_release(bind_to_dik(game_action))
		end
	)
end

local reset_lookout_states = {
	[hud_state.eShowing] = true,
	[hud_state.eHidden] = true,
	[hud_state.eHiding] = true,
	[hud_state.eReload] = true,
}

function on_state_switch(item, state, old_state)
	if get_console():get_bool("g_hold_to_lookout") then
	return end
	if not reset_lookout_states[state] then
	return end
	if not IsMoveState(move_state.mcLookout) then
	return end
	SetMoveState(move_state.mcLookout, false)
end

-- local test_particles = {
	-- ["cam_pos"] = particles_object([[_samples_particles_\gt_glow_large_bright_white]]),
	-- ["rotation_pos"] = particles_object([[_samples_particles_\gt_glow_large_bright_blue]]),
	-- ["pos_left"] = particles_object([[_samples_particles_\gt_glow_large_bright_red]]),
	-- ["pos_right"] = particles_object([[_samples_particles_\gt_glow_large_bright_green]]),
	-- ["pos_up"] = particles_object([[_samples_particles_\gt_glow_large_bright_cyan]]),
-- }
function on_hud_item_zoom_in(item)
	-- for k,v in pairs(test_particles) do
		-- v:stop()
	-- end
	if not get_script_option_value("auto_lookout") then
	return end
	if IsMoveState(move_state.mcLookout) then
	return end
	local pos = device().cam_pos
	--log_news("pos.y [%s]", pos.y)
	--test_particles["cam_pos"]:play_at_pos(pos)
	local dir = device().cam_dir
	--//forward parallel to ground
	local forward = vector():set(dir):normalize()
	--forward.y = 0
	if forward:magnitude() < 0.001 then
		--log_news("looking up")
	return end
	
	local rq = level.ray_query(pos, forward, auto_lookout_dist, rq_target.rqtBoth, actor)
	if not rq.result then
		--log_news("forward has no obstacle")
	return end

	local cur_box_id = actor_obj.ph_box_id
	--log_news("cur_box_id [%s]", cur_box_id)
	if cur_box_id == 1 or cur_box_id == 2 then
		up_box_id = cur_box_id + 2
		local up_box = ph_box[up_box_id]
		if up_box then
			local pos_up = vector():set(pos)
			pos_up.y = actor:position().y + cam_height_factor * up_box.y
			--log_news("pos_up.y [%s]", pos_up.y)
			--test_particles["pos_up"]:play_at_pos(pos_up)
			rq = level.ray_query(pos_up, forward, auto_lookout_dist, rq_target.rqtBoth, actor)
			if not rq.result then
				--log_news("up has no obstacle")
				auto_lookout = true
				actor_obj.ph_box_id = up_box_id
			return end
		end
	end

	local lookout_angle = actor_obj.lookout_angle

	local rotation_pos = vector():set(pos)
	rotation_pos.y = rotation_pos.y - (pos.y - actor:position().y) * 0.25
	--log_news("rotation_pos.y [%s]", rotation_pos.y)
	--test_particles["rotation_pos"]:play_at_pos(rotation_pos)
	
	local rotation_vector = pos:sub(rotation_pos)
	local rotation_length = rotation_vector:magnitude()
	--log_news("rotation_length [%s]", rotation_length)
	
	local rotation_left = rodrigues_rotate(rotation_vector, forward, lookout_angle)
	local pos_left = vector():mad(rotation_pos, rotation_left:normalize(), rotation_length)
	--test_particles["pos_left"]:play_at_pos(pos_left)
	rq = level.ray_query(pos_left, forward, auto_lookout_dist, rq_target.rqtBoth, actor)
	if not rq.result then
		--log_news("left has no obstacle")
		auto_lookout = true
		SetMoveState(move_state.mcLLookout, true)
	return end
	
	local rotation_right = rodrigues_rotate(rotation_vector, forward, -lookout_angle)
	local pos_right = vector():mad(rotation_pos, rotation_right:normalize(), rotation_length)
	--test_particles["pos_right"]:play_at_pos(pos_right)
	rq = level.ray_query(pos_right, forward, auto_lookout_dist, rq_target.rqtBoth, actor)
	if not rq.result then
		--log_news("right has no obstacle")
		auto_lookout = true
		SetMoveState(move_state.mcRLookout, true)
	return end
end

function on_hud_item_zoom_out(item)
	if not auto_lookout then
	return end
	--log_news("disable auto_lookout")
	auto_lookout = false
	SetMoveState(move_state.mcLookout, false)
	if up_box_id then
		local cur_box_id = actor_obj.ph_box_id
		if cur_box_id == up_box_id and not IsMoveState(move_state.mcAnyMove) then
			actor_obj.ph_box_id = up_box_id - 2
		end
		up_box_id = false
	end
end