-- -*- mode: lua; coding: windows-1251-dos -*-
function attach(sm)
	sm:subscribe({signal = "on_key_press",   		fun = this.on_key_press})
end

local console = get_console()
local hud_sect = "swipe_mask_hud"
local hud_anm = "camera_effects\\item_use\\two_handed_weapon_effect.anm"
local hud_effector_id = 5556
local smear_dec = 0.01
local smear_max = 2

function on_key_press(key, game_action)
	local mir = level.main_input_receiver()
	local pda_wnd = level.get_pda_wnd():GetPdaWnd()
	if (mir and (mir:WindowName() ~= pda_wnd:WindowName() or not is_3d_pda())) or 
		game_action ~= key_bindings.kSWIPE_MASK or
		not actor_hands_free() or
		not console:get_bool("r2_rain_drops_control")
	then
	return end
	
	-- local wpn = actor:active_item() and actor:active_item():get_weapon()
	-- if wpn and wpn.zoom_mode then
		-- wpn:zoom_out()
	-- end
	local was_zoomed = false
	if actor:active_item() and actor:active_item():is_zoomed() then
		actor:active_item():zoom_out()
		was_zoomed = true
	end
	
	if was_zoomed then
		level.add_call(
			function()
				return actor_hands_free()
			end,
			function()
				if actor:active_item() then
					actor:active_item():zoom_in()
				end
			end
		)
	end
	
	game.play_hud_motion(1, hud_sect, "anm_use", false, 1, false)
	local snd_name = read_if_exists(sys_ini, "string", hud_sect, "hud_sound", nil)
	xr_sound.get_safe_sound_object(snd_name..math.random(1,3)):play_no_feedback(actor, sound_object.s2d, 0, vector(), 1.0)
	local eff_name = read_if_exists(sys_ini, "string", hud_sect, "hud_effector", nil)
	level.add_complex_effector(eff_name, hud_effector_id)
	game.play_hud_anm(hud_anm, 0, 2.2, 0.5, false)
	
	--//щоб крапельки зникали відповідно до анімації
	add_time_delayed_action(
		read_if_exists(sys_ini, "float", hud_sect, "use_delay", 1.5),
		function()
			console:execute("r2_rain_drops_control off")
			local smear_texture_idx = math.random(1,4)
			shader_set_custom_param("raindrop_restart", smear_max, smear_texture_idx)
			level.add_call(
				function()
					local smear = math.clamp(shader_get_custom_param("raindrop_restart") - smear_dec, 0, smear_max)
					shader_set_custom_param("raindrop_restart", smear, smear_texture_idx)
					return shader_get_custom_param("raindrop_restart") <= 0
				end,
				function()
				end
			)
		end
	)
		
	add_time_delayed_action(
		read_if_exists(sys_ini, "float", hud_sect, "restore_delay", 1.5),
		function()
			console:execute("r2_rain_drops_control on")
		end
	)
end