-- -*- mode: lua; coding: windows-1251-dos -*-
function attach(sm)
	sm:subscribe({signal = "on_actor_weapon_zoom_in",   fun = this.on_zoom_in})
end

local ezi = false
local base_k = false
local zoom_factor = 1
local aimed_weapon
local subscribed = false

local DEBUG_DISABLE = false

local ZOOM_SOMNOLENCE_K = read_if_exists(sys_ini, "float", "actor_condition", "somnolence_zoom_effector_k", 1)
local CROUCH_K = 0.25

function get_zoom_effector_k()
	local crouch_k = 1
	if actor_obj:is_actor_crouch() then
		crouch_k = CROUCH_K
	end
	--log_news("ZOOM_SOMNOLENCE_K [%s] somnolence.get_val() [%s] zoom_factor [%s] crouch_k [%s]", ZOOM_SOMNOLENCE_K, somnolence.get_val(), zoom_factor, crouch_k)
	return (1 + (ZOOM_SOMNOLENCE_K * somnolence.get_val()))/zoom_factor * crouch_k
end

function on_zoom_in(weapon)
	zoom_factor = weapon:get_zoom_factor()
	aimed_weapon = weapon
	--log_news("zoom_factor on zoom [%s]", zoom_factor)
	if not subscribed then
		subscribed = {
			{ signal = "on_update", 				fun = this.on_update },
			{ signal = "on_actor_weapon_zoom_out", 	fun = this.on_zoom_out},
		}
		local sm = ogsr_signals.get_mgr()
		for _, s in ipairs( subscribed ) do
			sm:subscribe( s )
		end
	end
end

function on_zoom_out(weapon)
	if subscribed then
		local sm = ogsr_signals.get_mgr()
		for _, s in ipairs( subscribed ) do
			sm:unsubscribe( s )
		end
		subscribed = false
	end
	ezi = false
	base_k = false
	zoom_factor = 1
	aimed_weapon = false
end

function on_update(delta)
	if not ezi then
		ezi = find_effector_zi()
		if not ezi then
		return end
		base_k = ezi.zoom_aim_disp_k
		--log_news("base_k [%s]", base_k)
	end
	--log_news("get_zoom_effector_k [%s]", get_zoom_effector_k())
	ezi.zoom_aim_disp_k = base_k * get_zoom_effector_k()
	ezi.pause_effect = DEBUG_DISABLE or weapon_hardhold.is_hard_hold() or (aimed_weapon and aimed_weapon:is_item_hud_shown())--ui_scope_texture.has_scope_static()
end